# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90a05262c8e90d8f7a4af65c72ca47b7a12b87f197b164a52519f1f98546acd4c1f5b95b802db2434d8b3a4d450fed17a55ff13128224ab918125f44ad33c34b

test:
  secret_key_base: 1a8574f4f9c3f9f85c70a47ea16a0b834c467dbf6a42317bde44ae87a2986d0e375fbe5a6ed3aaa3fd1a70820121e051d6e0e57d642606c0f99c27ecdfc3b031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
